robot:
  wheel_radius: 0.027216 # radius of the large wheels in meters
  width:  0.13 # measure the wheel-to-wheel width of your robot and put it here. It is also in meters (so 0.2 = 20cm)
  delta_t: 0.1 # in seconds

camera:
  y_offset: 0 # where is the camera in relation to the robot's centre
  z_offset: 0 # where is the camera in relation to the robot's centre
  y_angle: 0 # in radians. 0 would mean that the robot is looking straight up, 90Â° means that the camera is pointing forward parallel to the floor.
  exposure_time: 60
  gain: 100

ekf_slam:
  robot_width: 0.2 # measure the wheel-to-wheel width of your robot and put it here. It is also in meters (so 0.2 = 20cm)
  motor_std: 4 # std = standard deviation. You might need to adjust these values depending on your motors, robot construction etc.
  dist_std: 0.1 # std = standard deviation. You might need to adjust these values depending on your motors, robot construction etc.
  angle_std: 4 # std = standard deviation. You might need to adjust these values depending on your motors, robot construction etc.

